### PR TITLE
Apply filters on resource removal

### PR DESCRIPTION
**Pull request by asiragusa**
This PR allows external functions to purge the cache, adding a lot of flexibility to this plugin.

I added the following filters:

```
rt_nginx_helper_purging_url
rt_nginx_helper_purging_all
rt_nginx_helper_purging_wildcard
```

### CODE REVIEW

**Comment by asiragusa** [comment]
Any news on this?

**Comment by xavivars** [comment]
This would be really useful if implemented...

**Comment by asiragusa** [comment]
@xavivars Well, with this PR it's actually quite easy to implement a filter to do the job. If you want I can give you some usage examples.

**Comment by chandra-patel** [comment]
Hello @asiragusa 

I'm sorry for late response and thanks for the PR.

Can you please give some usage examples?

Regards,
Chandra

**Pull request closed without merging**
