### PR TITLE
Purge All to follow purge_method

### PR DESCRIPTION
**Pull request by dotsam**
If the user has picked GET requests for their purge method, let's use that for "Purge All" too.

### CODE REVIEW

**Comment by dotsam** [comment]
Any consideration to this PR? It's been well-documented that this can cause issues with timeouts for large sites, but it's really the only option to purge a single site's cache in a multi-user environment.

**Comment by chandra-patel** [comment]
Hello @dotsam 

I am sorry for delay. I will look into it. Thanks.

**Comment by rahul286** [comment]
@dotsam 

> It's been well-documented that this can cause issues with timeouts for large sites, but it's really the only option to purge a single site's cache in a multi-user environment.

Did you try redis full page cache? https://easyengine.io/blog/easyengine-3-3-full-page-redis-cache/

Problem is - after this code merge, default behavior to purge entire cache will be switched to GET method. This will create problem for single sites. 

I am concerned about this. May be we need two defaults.

1. Single page purge - default GET
2. Purge entire cache - default unlink filesystem-recursive method

**Comment by dotsam** [comment]
Yes, with this PR, the default would be to purge both single pages or purge all with GET requests. If the filesystem method is selected, then both single pages and purge all then switch to deleting directly from the filesystem.

The issue I'm seeking to avoid is the fact that if the filesystem is inaccessible to the web server user, then "Purge All" doesn't do anything at all. I'd be fine having two options for how each purge should work, but it seems to me that if you don't have filesystem working for single page, it won't work for purge all either, and thus it doesn't make a lot of sense to have two settings.

**Comment by rahul286** [comment]
> filesystem is inaccessible to the web server user

In this case nginx may not be able to create pages in cache. 

If you are running nginx and php under different system users, then you may use some other workaround. Few things immediately coming to mind are:

1. user/group permission
2. chmod 0777 for cache folder
3. move cache path to /tmp which is read-write by all

Sorry but making purge-all defaults to GET method will create issue for many arge sites which are currently running fine. This plugin is installed and configured by default in EasyEngine - https://github.com/easyengine/easyengine

**Comment by dotsam** [comment]
I think the biggest issue here is that currently, even with the default purge method of "GET" selected, the purge all doesn't follow that, and does a filesystem purge. This behaviour is counterintuitive to the settings the user has chosen, and isn't actually spelled out that way for the user anywhere obvious.

Moving forward, I think there absolutely needs to be a way to specify how a purge all is done. I see your point about how pushing this change out would affect existing installs that are still set to the "GET" method, but in reality use the filesystem purge method via the "Purge All" button.

What's the solution moving forward here? Do we add a separate setting for how "purge all" works, and carry that forward? Or should we add a secondary hidden setting for this and set it to "filesystem" on upgrades where it doesn't exist, and then have it follow the displayed "purge method" setting when it is changed after that?

**Comment by rahul286** [comment]
> What's the solution moving forward here?

We need to add separate setting for "purge all".

This will be default to "filesystem" on upgrades where it doesn't exist. 

You have described it quite correctly. :-)

**Comment by dotsam** [comment]
Rebased off master and updated to include a discrete option to set purge all method, which defaults to using the filesystem purge.

**Comment by chandra-patel** [comment]
Hi @dotsam 

I'm sorry for late response. I will test this PR and will let you know.

Regards,
Chandra

**Comment by danimalweb** [comment]
I'd love to see this PR merged.

**Pull request closed without merging**
