### PR TITLE
Purge a single site in subfolder multisite setups

### PR DESCRIPTION
**Pull request by larssn**
- Purging a single site in a subfolder multisite setup now works.
- Minor code cleanup.

If your domain is setup as www.example.com/site1/, www.example.com/site2/ etc., then pressing the "Purge Cache" button on one of those sites will now only purge the cache for that site. Tested and working.

Same should be true for subdomain multisite setups.

Ps. Don't merge the readme file.

### CODE REVIEW

**Comment by chandra-patel** [comment]
Hello @larssn 

Thanks for the PR. I applied different solution to purge single site cache in multisite setup. It's work for both sub-domain and sub-directory site. Please check my commit https://github.com/rtCamp/nginx-helper/commit/c4dc90dbe248e883cb46f0a4f8a1108c3f26e627

I haven't merge this PR as it contain more changes and for the main issue I applied different solution.

Please let me know your wordpress.org username so I can add in contributors list.

Thanks again.

**Comment by chandra-patel** [comment]
Hello @larssn

I have released the plugin. Please check. Thanks for your help.

**Comment by larssn** [comment]
Cool, it looks like that would purge correctly. Gonna test it.

**Comment by larssn** [comment]
So there's still an issue if you're using domain mapping:
When standing on the network admin page, and pressing purge cache it deletes the cache of all sites - a function that i'd prefer the big red button doing, under settings.

Lemme explain. So if Redis contains this:
1) "nuvoweb-cache:httpsGETwww.asia-slagelse.dk/"
2) "nuvoweb-cache:httpsGETcloud.nuvoweb.dk/"
3) "nuvoweb-cache:httpsGETcloud.nuvoweb.dk/ye-sushi/cart/"
4) "nuvoweb-cache:httpsGETcloud.nuvoweb.dk/ye-sushi/produkt/"
5) "nuvoweb-cache:httpGETwww.onekey.dk/"
6) "nuvoweb-cache:httpGETnuvoweb.dk/"

.. and I'm standing in the network admin page at cloud.nuvoweb.dk/network, and press "Purge Cache", then the entire cache is deleted, including onekey and asia, which are different domains.

I had fixed this in this pull request, by adding a new helper action called "site", that only purges the cache for a single domain.

**Comment by chandra-patel** [comment]
Hello @larssn

The interface might be confusing. 

If you Purge Cache from Network Admin then it will purge all site cache in WPMU. 

If you want to purge cache of individual site then goto the individual site dashboard and click on Purge Cache button.

Let me know if this make sense.

Regards,

**Comment by larssn** [comment]
Yeah I get it, maybe my example didn't make sense.
Anyway, your code, your choice. My fork needs to do it my way though. :)

**Pull request closed without merging**
